
import os
import re
from pathlib import Path

# Paths relative to this script
SCRIPT_DIR = Path(__file__).parent.resolve()
ASSETS_DIR = SCRIPT_DIR / "assets"
HTML_OUTPUT = SCRIPT_DIR / "gallery.html"

def generate_html(models_data, all_resolutions):
    """
    Generates the HTML gallery grouped by Model ID.
    models_data: {
        'uid': {
            'glb': path_to_glb,
            'renders': { 20: path_to_png, 32: path_to_png, ... }
        }
    }
    all_resolutions: Sorted list of all resolution integers found [20, 32, 50]
    """
    
    # Calculate grid columns: 1 (Original) + N (Resolutions)
    col_count = 1 + len(all_resolutions)
    
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BrickGPT: Comparison Gallery</title>
    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js"></script>
    <style>
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #f0f2f5; padding: 20px; color: #333; }}
        h1 {{ text-align: center; margin-bottom: 40px; color: #1a1a1a; }}
        
        .model-section {{ 
            background: white;
            border-radius: 16px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.06);
            margin-bottom: 40px;
            overflow: hidden;
            padding: 0;
        }}
        
        .model-header {{
            background: #2c3e50;
            color: white;
            padding: 15px 25px;
            font-size: 1.1em;
            font-weight: 500;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        
        .comparison-grid {{
            display: grid;
            grid-template-columns: repeat({col_count}, 1fr);
            gap: 0;
            divider: 1px solid #eee;
        }}
        
        .grid-item {{
            border-right: 1px solid #eee;
            position: relative;
            background: #fff;
            aspect-ratio: 4/3; /* Standardize aspect ratio */
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }}
        
        .grid-item:last-child {{ border-right: none; }}
        
        .label {{
            position: absolute;
            top: 10px;
            left: 10px;
            background: rgba(0,0,0,0.7);
            color: white;
            padding: 4px 10px;
            font-size: 12px;
            border-radius: 20px;
            z-index: 10;
            backdrop-filter: blur(4px);
            font-weight: 500;
        }}
        
        model-viewer {{ width: 100%; height: 100%; }}
        img {{ max-width: 90%; max-height: 90%; object-fit: contain; transition: transform 0.2s; }}
        
        .missing-placeholder {{
            color: #ccc;
            font-style: italic;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>Objaverse vs LEGO Resolution Comparison</h1>
    """

    for uid, data in models_data.items():
        glb_rel = os.path.relpath(data['glb'], SCRIPT_DIR)
        
        html_content += f"""
        <div class="model-section">
            <div class="model-header">
                <span>Model: {uid}</span>
            </div>
            <div class="comparison-grid">
                <!-- 1. Original 3D Model -->
                <div class="grid-item">
                    <div class="label">Original (GLB)</div>
                    <model-viewer 
                        src="{glb_rel}" 
                        auto-rotate camera-controls 
                        shadow-intensity="1"
                        interaction-prompt="none">
                    </model-viewer>
                </div>
        """
        
        # 2. Render Columns (Sorted)
        for res in all_resolutions:
            png_path = data['renders'].get(res)
            
            if png_path:
                png_rel = os.path.relpath(png_path, SCRIPT_DIR)
                content = f'<img src="{png_rel}" alt="Res {res}">'
            else:
                content = '<span class="missing-placeholder">Not generated</span>'
                
            html_content += f"""
                <div class="grid-item">
                    <div class="label">Res {res}</div>
                    {content}
                </div>
            """
            
        html_content += """
            </div>
        </div>
        """

    html_content += """
    <footer style="text-align: center; margin-top: 50px; color: #888;">
        Generated by BrickGPT
    </footer>
</body>
</html>
    """
    
    return html_content

def main():
    if not ASSETS_DIR.exists():
        print(f"Error: assets directory not found at {ASSETS_DIR}")
        return

    # Data Structure:
    # models = { 'uid': { 'glb': path, 'renders': {20: path, 32: path} } }
    models = {}
    all_resolutions = set()

    # 1. Find all available original GLB files in the root of assets/
    #    (or wherever download_obj.py puts them)
    #    We scan ASSETS_DIR for .glb
    glb_files = list(ASSETS_DIR.glob("*.glb"))
    print(f"Found {len(glb_files)} source GLB files.")

    for glb in glb_files:
        uid = glb.stem
        models[uid] = {
            'glb': glb,
            'renders': {}
        }

    # 2. Scan all resolution subfolders
    res_dirs = list(ASSETS_DIR.glob("res_*"))
    for r_dir in res_dirs:
        # Parse resolution from folder name
        parts = r_dir.name.split("_")
        if len(parts) < 2 or not parts[1].isdigit():
            continue
            
        res = int(parts[1])
        all_resolutions.add(res)
        
        # Find PNGs in this resolution folder
        png_files = list(r_dir.glob("*.png"))
        
        for png in png_files:
            uid = png.stem
            # If we don't know this UID from a GLB (e.g. GLB was deleted?), skip or add placeholder?
            # Let's focused on mapped models first.
            if uid in models:
                models[uid]['renders'][res] = png
            else:
                # Optional: Handle orphan renders if needed, but usually we care about the comparison
                pass

    sorted_res = sorted(list(all_resolutions))
    print(f"Found resolutions: {sorted_res}")
    
    # Filter out models that have NO renders at all? 
    # Or keep them to show they failed? 
    # Let's keep them so you can see the original at least.

    # Generate HTML
    total_models = len(models)
    print(f"Generating gallery for {total_models} models...")
    
    with open(HTML_OUTPUT, "w") as f:
        f.write(generate_html(models, sorted_res))
        
    print("-" * 40)
    print(f"Gallery refactored successfully!")
    print(f"Open this file in your browser: {HTML_OUTPUT}")

if __name__ == "__main__":
    main()
